clean:
	rm *pbs.e* *pbs.o*

clean_results:
	rm tests/omp/cpu/* tests/omp/memory/* tests/omp/io/* || true
	rm tests/ser/cpu/* tests/ser/memory/* tests/ser/io/* || true
	rm tests/mpi/cpu/* tests/mpi/memory/* tests/mpi/io/* || true
	rm tests_part_2/omp/cpu/* tests_part_2/omp/memory/* tests_part_2/omp/io/* || true
	rm tests_part_2/ser/cpu/* tests_part_2/ser/memory/* tests_part_2/ser/io/* || true
	rm tests_part_2/ser/cpu/* tests_part_2/ser/memory/* tests_part_2/ser/io/* || true
	
