#!/bin/bash
#PBS -l nodes=1:ppn=32:r641
#PBS -l walltime=02:00:00
#PBS -V

module load gcc/5.3.0

cd esc-nas/NPB3.3.1/NPB3.3-OMP

#cp config/NAS.samples/suite.def.is config/suite.def
#cp config/NAS.samples/make.def.gcc_x86 config/make.def

##make clean
##make suite

cd ..
cd ..

cpu="tests_part_2/ser/cpu/$test_file.txt"
memory="tests_part_2/ser/memory/$test_file.txt"
io="tests_part_2/ser/io/$test_file.txt"

sar 1 >> $cpu &
sar -r 1 >> $memory &
sar -b 1 >> $io &

for((d = 0; d < tests; d++))
do
	for((i = 0; i < repetitions; i++))
	do
		./NPB3.3.1/NPB3.3-SER/bin/$test_exe
	done
	
	echo "#test $d" >> $cpu
	echo "#test $d" >> $memory
	echo "#test $d" >> $io
	
done

